### ISSUE TITLE
Migrate to Node.js native test runner

### ISSUE THREAD

**Issue by fraxken** [NodeSecure/flags#37]
Remove tape (and packages related like `@small-tech/esm-tape-runner`) to use the Node.js native runner.

https://nodejs.org/api/test.html

[i18n](https://github.com/NodeSecure/i18n) and [utils](https://github.com/NodeSecure/utils) has been migrated few days ago (so do not hesitate to check the scripts and tests).

**Comment by MaximeMRF** [comment]
I take it

**Comment by fraxken** [comment]
@MaximeMRF Are you doing it?

**Comment by MaximeMRF** [comment]
@fraxken I'm doing it, I haven't had much time in the last few weeks
